#!/usr/bin/env groovy

// options { buildDiscarder(logRotator(numToKeepStr: '5')) }


node {
    stage('Init Stage'){
        env.APP_NAME = "spr-monolith"
        env.ACR_NAME = "testrigregistry"
        env.SUBSCRIPTION_ID = "57b13db8-88cf-4fe6-924b-ae10dc6fadee"
        env.AKS_NAME = "demo-aks"
        env.RESOURCE_GROUP = "demo-rg"
        env.BRANCH_NAME = "seeder"        
    }

    stage('GitCheckout'){
        checkout scm
    }

    // stage('LocalBuild'){
    //     sh './mvnw install'
    // }

    stage('LocalDockerBuild'){
        sh 'time docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -w /usr/src/mymaven maven:3.3-jdk-8 mvn install'
    }

    // stage('LocalDockerBuild'){
    //     sh 'docker build -t jim -f seeder/Dockerfile .'
    // }


    // stage('AzureBuild'){
    // withCredentials([azureServicePrincipal('test-rig-demo-jenkins')]) {  
    //     sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
    //     sh 'az acr build --file seeder/Dockerfile --subscription  ${SUBSCRIPTION_ID}   --registry ${ACR_NAME} --image ${APP_NAME}:${BRANCH_NAME} .'
    // }}
}


 
