pipeline {
    agent {
        label 'linux'
    }
    stages {
        stage('GitCheckout'){
            steps{
                sh 'echo Git Checkout'
                checkout scm
                sh 'ls -l '
            }}


        stage('Testing') {
            steps {
                sh 'echo Testing'
                sh 'mvn mvn -f /tmp/pom.xml -B -s seed/maven/ref/settings-docker.xml -Dtest=PetControllerTests surefire:test  '
            }
        }
    }
}