pipeline {
    agent none
    stages {
        stage('Tests') {
            
            parallel {
                stage('JaCoCo') {
                    agent {
                        label "maven"
                    }
                    steps {
                        // checkout scm
                        sh "#mvn -B -s /usr/share/maven/ref/repository/settings-docker.xml jacoco:report-aggregate"
                        sh "echo JaCoCo"
                    }
                    // post {
                    //     always {
                    //         junit "**/TEST-*.xml"
                    //     }
                    // }
                }
                stage('Integration') {
                    agent {
                        label "maven"
                    }
                    steps {
                        // checkout scm
                        sh "mvn -B -s /usr/share/maven/ref/repository/settings-docker.xml surefire:test"
                    }
                    // post {
                    //     always {
                    //         junit "**/TEST-*.xml"
                    //     }
                    // }
                }
                stage('Model') {
                    agent {
                        label "maven"
                    }
                    steps {
                        // checkout scm
                        sh "mvn -B -s /usr/share/maven/ref/repository/settings-docker.xml surefire:test"
                    }
                    // post {
                    //     always {
                    //         junit "**/TEST-*.xml"
                    //     }
                    // }
                }
                stage('Owner') {
                    agent {
                        label "maven"
                    }
                    steps {
                        // checkout scm
                        sh "mvn -B -s /usr/share/maven/ref/repository/settings-docker.xml surefire:test " 
                    }
                    // post {
                    //     always {
                    //         junit "**/TEST-*.xml"
                    //     }
                    // }
                }
                stage('Service') {
                    agent {
                        label "maven"
                    }
                    steps {
                        // checkout scm
                        sh "mvn -B -s /usr/share/maven/ref/repository/settings-docker.xml surefire:test  "
                    }
                    // post {
                    //     always {
                    //         junit "**/TEST-*.xml"
                    //     }
                    // }
                }
                stage('System') {
                    agent {
                        label "maven"
                    }
                    steps {
                        // checkout scm
                        sh "mvn -B -s /usr/share/maven/ref/repository/settings-docker.xml surefire:test"
                    }
                    // post {
                    //     always {
                    //         junit "**/TEST-*.xml"
                    //     }
                    // }
                }
                stage('Vet') {
                    agent {
                        label "maven"
                    }
                    steps {
                        // checkout scm
                        sh "mvn -B -s /usr/share/maven/ref/repository/settings-docker.xml surefire:test"
                    }
                    // post {
                    //     always {
                    //         junit "**/TEST-*.xml"
                    //     }
                    // }
                }










                stage('jMeter') {
                    agent {
                        label "maven"
                    }
                    steps {
                        // checkout scm
                        sh "echo jMeter should be here"
                    }
                    // post {
                    //     always {
                    //         junit "**/TEST-*.xml"
                    //     }
                    // }
                }
            }
        }
    }
}




