pipeline {
    agent none
    stages {
        stage('Run Tests') {
            parallel {
                stage('JaCoCo Testing') {
                    agent {
                        label "maven"
                    }
                    steps {
                        bat "mvn -B -s /usr/share/maven/ref/repository/settings-docker.xml jacoco:report-aggregate"
                    }
                    post {
                        always {
                            junit "**/TEST-*.xml"
                        }
                    }
                }
                stage('Surefiretests') {
                    agent {
                        label "maven"
                    }
                    steps {
                        sh "mvn -B -s /usr/share/maven/ref/repository/settings-docker.xml surefire:test"
                    }
                    post {
                        always {
                            junit "**/TEST-*.xml"
                        }
                    }
                }
            }
        }
    }
}




